Update pieplinework.yml

diff --git a/.github/workflows/pieplinework.yml b/.github/workflows/pieplinework.yml
--- a/.github/workflows/pieplinework.yml
+++ b/.github/workflows/pieplinework.yml
@@ -21,33 +21,33 @@ jobs:
           ref: main  # Ensure the branch exists
           path: sca_managment
 
-      # - name: Generate .trivyignore from centralized ignore list
-      #   run: |
-      #     echo "🔍 Extracting ignored CVEs for this repository..."
+      - name: Generate .trivyignore from centralized ignore list
+        run: |
+          echo "🔍 Extracting ignored CVEs for this repository..."
       
-      #     FULL_REPO="${{ github.repository }}"          # e.g. ninza-test/slack-pr-approval
-      #     REPO_NAME=$(basename "$FULL_REPO")            # Extract 'slack-pr-approval'
+          FULL_REPO="${{ github.repository }}"          # e.g. ninza-test/slack-pr-approval
+          REPO_NAME=$(basename "$FULL_REPO")            # Extract 'slack-pr-approval'
       
-      #     JSON_FILE="sca_managment/cveignore.json"
-      #     TRIVYIGNORE=".trivyignore"
+          JSON_FILE="sca_managment/cveignore.json"
+          TRIVYIGNORE=".trivyignore"
       
-      #     echo "📦 Current repository: $REPO_NAME"
-      #     echo "📄 Using JSON file: $JSON_FILE"
+          echo "📦 Current repository: $REPO_NAME"
+          echo "📄 Using JSON file: $JSON_FILE"
       
-      #     if [ ! -f "$JSON_FILE" ]; then
-      #       echo "❌ JSON file not found at $JSON_FILE"
-      #       exit 1
-      #     fi
+          if [ ! -f "$JSON_FILE" ]; then
+            echo "❌ JSON file not found at $JSON_FILE"
+            exit 1
+          fi
       
-      #     MATCH=$(jq -r "has(\"$REPO_NAME\")" "$JSON_FILE")
-      #     if [ "$MATCH" != "true" ]; then
-      #       echo "⚠️  No ignored CVEs found for repo: $REPO_NAME"
-      #       touch "$TRIVYIGNORE"
-      #     else
-      #       jq -r ".\"$REPO_NAME\".ignored_cves[].cve_id" "$JSON_FILE" > "$TRIVYIGNORE"
-      #       echo "✅ .trivyignore created with the following CVEs:"
-      #       cat "$TRIVYIGNORE"
-      #     fi
+          MATCH=$(jq -r "has(\"$REPO_NAME\")" "$JSON_FILE")
+          if [ "$MATCH" != "true" ]; then
+            echo "⚠️  No ignored CVEs found for repo: $REPO_NAME"
+            touch "$TRIVYIGNORE"
+          else
+            jq -r ".\"$REPO_NAME\".ignored_cves[].cve_id" "$JSON_FILE" > "$TRIVYIGNORE"
+            echo "✅ .trivyignore created with the following CVEs:"
+            cat "$TRIVYIGNORE"
+          fi
 
       - name: heloc hecking
         run: |
